/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.JOptionPane;
import java.sql.*;
public class addpolice extends javax.swing.JFrame {
     Connection myConn = null;
     
    public addpolice() {
        initComponents();
        myConn = DbConn.connect();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        traffic_officer_email = new javax.swing.JTextField();
        qq = new javax.swing.JLabel();
        traffic_officer_full_name = new javax.swing.JTextField();
        aa = new javax.swing.JLabel();
        traffic_officer_password = new javax.swing.JTextField();
        vv = new javax.swing.JLabel();
        police_station = new javax.swing.JTextField();
        etpobutton = new javax.swing.JButton();
        atpobutton = new javax.swing.JButton();
        rtpobutton = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        traffic_officer_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Add Police Officer");

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Dashboard / Add Police Officer");

        jLabel4.setText("Taffic Officer Email");

        traffic_officer_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traffic_officer_emailActionPerformed(evt);
            }
        });

        qq.setText("Traffic Officer Full Name");

        traffic_officer_full_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traffic_officer_full_nameActionPerformed(evt);
            }
        });

        aa.setText("Traffic Officer Password");

        traffic_officer_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traffic_officer_passwordActionPerformed(evt);
            }
        });

        vv.setText("Police Station");

        etpobutton.setText("Edit Traffic Officer");
        etpobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etpobuttonActionPerformed(evt);
            }
        });

        atpobutton.setText("Add Traffic Officer");
        atpobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atpobuttonActionPerformed(evt);
            }
        });

        rtpobutton.setText("Remove Traffic Officer");
        rtpobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtpobuttonActionPerformed(evt);
            }
        });

        back1.setText("Back");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        jLabel2.setText("Traffic Officer ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aa)
                                .addGap(26, 26, 26)
                                .addComponent(traffic_officer_password, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(vv, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(traffic_officer_email, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qq, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42)
                                .addComponent(traffic_officer_id, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(traffic_officer_full_name)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(police_station, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 11, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etpobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(atpobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(rtpobutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Search)
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search)
                    .addComponent(jLabel2)
                    .addComponent(traffic_officer_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(traffic_officer_full_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(qq)
                        .addComponent(jLabel4)
                        .addComponent(traffic_officer_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aa)
                            .addComponent(traffic_officer_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vv)
                            .addComponent(police_station, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etpobutton)
                            .addComponent(atpobutton))
                        .addGap(18, 18, 18)
                        .addComponent(rtpobutton)
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back1)
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void traffic_officer_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traffic_officer_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traffic_officer_emailActionPerformed

    private void traffic_officer_full_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traffic_officer_full_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traffic_officer_full_nameActionPerformed

    private void traffic_officer_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traffic_officer_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traffic_officer_passwordActionPerformed

    private void etpobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etpobuttonActionPerformed
        // TODO add your handling code here:
        try{
            
                String update_police_officer_query = "UPDATE police_officer SET traffic_officer_email = '" + traffic_officer_email.getText() 
                        +"', traffic_officer_full_name ='"+ traffic_officer_full_name.getText() 
                        +"', traffic_officer_password ='"+ traffic_officer_password.getText() 
                        +"', police_station ='"+ police_station.getText()+"'" ;
                PreparedStatement pst = myConn.prepareStatement(update_police_officer_query); 
                pst.execute();
                JOptionPane.showMessageDialog(null, "The police officer was edited!");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "The police officer was not edited!");
            System.out.println("The error was" + e);
        }
    }//GEN-LAST:event_etpobuttonActionPerformed

    private void atpobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atpobuttonActionPerformed
        // TODO add your handling code here:
        try{
            if(  traffic_officer_email.getText().equals("")
                 ||traffic_officer_full_name.getText().equals("")||traffic_officer_password.getText().equals("")
                 ||police_station.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Please ensure to fill out all necessary informations!");
            }
            else{
                String save_police_officer_query = "INSERT INTO police_officer("+"`traffic_officer_email`,`traffic_officer_full_name`,`traffic_officer_password`,`police_station`)"
                     +"VALUES('"+traffic_officer_email.getText()+"','"+traffic_officer_full_name.getText()+"','"
                     +traffic_officer_password.getText()+"','"
                     +police_station.getText()+"')";
                PreparedStatement pst = myConn.prepareStatement(save_police_officer_query); 
                pst.execute();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "The police officer was not saved!");
            System.out.println("The error was" + e);
        }
        
    }//GEN-LAST:event_atpobuttonActionPerformed

    private void rtpobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtpobuttonActionPerformed
        // TODO add your handling code here:
          try{
                int traffic_officer_id1 = Integer.parseInt(traffic_officer_id.getText());
                String delete_police_officer_query = "DELETE FROM police_officer where traffic_officer_id = " + traffic_officer_id1;
                PreparedStatement pst = myConn.prepareStatement(delete_police_officer_query); 
                pst.execute();
                JOptionPane.showMessageDialog(null, "The police officer was removed!");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "The police officer was not removed!");
            System.out.println("The error was" + e);
        }
    }//GEN-LAST:event_rtpobuttonActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here:
        PAlogin palog = new PAlogin();
        palog.show();//display PAlogin here
        dispose();//close current frame(addpolice) after opening PAlogin
    }//GEN-LAST:event_back1ActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        try{
            
            int traffic_officer_id1 = Integer.parseInt(traffic_officer_id.getText());
            String q1 = "SELECT * FROM `police_officer` WHERE traffic_officer_id = '" +traffic_officer_id1+"'";
            PreparedStatement pst1 = myConn.prepareStatement(q1);
            ResultSet rs = pst1.executeQuery();
            String traffic_officer_email1 = ""; 
            String traffic_officer_full_name1 = "";
            String traffic_officer_password1 = "";
            String police_station1 = "";
            while(rs.next()) {
                 traffic_officer_email1= rs.getString("traffic_officer_email");
                 traffic_officer_full_name1=  rs.getString("traffic_officer_full_name");
                 traffic_officer_password1 = rs.getString("traffic_officer_password");
                 police_station1 = rs.getString("police_station");
                 
            }
            traffic_officer_email.setText(traffic_officer_email1);
            traffic_officer_full_name.setText(traffic_officer_full_name1);
            traffic_officer_password.setText(traffic_officer_password1);
            police_station.setText(police_station1);
            
        }
        catch(Exception e1){
            System.out.println("The error was" + e1);
        }
    }//GEN-LAST:event_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addpolice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addpolice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addpolice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addpolice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addpolice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JLabel aa;
    private javax.swing.JButton atpobutton;
    private javax.swing.JButton back1;
    private javax.swing.JButton etpobutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField police_station;
    private javax.swing.JLabel qq;
    private javax.swing.JButton rtpobutton;
    private javax.swing.JTextField traffic_officer_email;
    private javax.swing.JTextField traffic_officer_full_name;
    private javax.swing.JTextField traffic_officer_id;
    private javax.swing.JTextField traffic_officer_password;
    private javax.swing.JLabel vv;
    // End of variables declaration//GEN-END:variables
}
